on: [push, pull_request]

name: R-winos

jobs:
  winos_check: 
  runs-on: windows-latest
  if: "!contains(github.event.head_commit.message, 'skip winos')"
  env:
    GITHUB_PAT: ${{secrets.GH_PAT}}
    R_KEEP_PKG_SOURCE: yes
  steps:
    - uses: actions/checkout@v3
  
    - uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true
  
    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: any::rcmdcheck
      needs: check
  
    - uses: r-lib/actions/check-r-package@v2
